/*
 * This file is generated by jOOQ.
 */
package com.golf;


import com.golf.tables.Golfer;
import com.golf.tables.records.GolferRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<GolferRecord, Integer> IDENTITY_GOLFER = Identities0.IDENTITY_GOLFER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<GolferRecord> GOLFER_ID_PK = UniqueKeys0.GOLFER_ID_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<GolferRecord, Integer> IDENTITY_GOLFER = Internal.createIdentity(Golfer.GOLFER, Golfer.GOLFER.GOLFER_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<GolferRecord> GOLFER_ID_PK = Internal.createUniqueKey(Golfer.GOLFER, "GOLFER_ID_PK", Golfer.GOLFER.GOLFER_ID);
    }
}
