/*
 * This file is generated by jOOQ.
 */
package com.golf;


import com.golf.tables.Golfer;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.GOLFER</code>.
     */
    public static final Golfer GOLFER = com.golf.tables.Golfer.GOLFER;
}
